# Generated by Django 5.1.6 on 2025-03-08 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_order_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["my_order"]},
        ),
        migrations.AddField(
            model_name="category",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="my_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="The phone number must start with +998 and consist of 9 characters.",
                        regex="^\\+998\\d{9}$",
                    )
                ],
            ),
        ),
    ]
